return {
	"marko-cerovac/material.nvim",
	config = function()
		require("material").setup({
			contrast = {
				terminal = false,
				sidebars = false,
				floating_windows = false,
				cursor_line = false,
				lsp_virtual_text = false,
				non_current_windows = false,
				filetypes = {},
			},
			styles = {
				comments = { italic = true },
				strings = { },
				keywords = { italic = true },
				functions = { bold = true},
				variables = {},
				operators = {},
				types = {},
			},
			plugins = {
				-- Uncomment the plugins that you use
				-- "coc",
				-- "colorful-winsep",
				-- "dap",
				-- "dashboard",
				-- "eyeliner",
				-- "fidget",
				-- "flash",
				-- "gitsigns",
				-- "harpoon",
				-- "hop",
				-- "illuminate",
				-- "indent-blankline",
				-- "lspsaga",
				-- "mini",
				-- "neogit",
				-- "neotest",
				-- "neo-tree",
				-- "neorg",
				-- "noice",
				-- "nvim-cmp",
				-- "nvim-navic",
				-- "nvim-tree",
				-- "nvim-web-devicons",
				-- "rainbow-delimiters",
				-- "sneak",
				-- "telescope",
				-- "trouble",
				-- "which-key",
				-- "nvim-notify",
			},
			disable = {
				colored_cursor = false,
				borders = false,
				background = false,
				term_colors = false,
				eob_lines = false,
			},
			high_visibility = {
				lighter = false,
				darker = false,
			},
			lualine_style = "default",
			async_loading = true,
			custom_colors = nil,
			custom_highlights = {},
		})
	end,
}
